### ISSUE TITLE
Fails to compile textures in lab

### ISSUE THREAD

**Issue by etcwilde** [marovira/atlas#1]
Atlas fails to compile with texture support on the lab machines.

**Comment by marovira** [comment]
This requires further investigation. It may be possible that the new release fixes it, but I'm not entirely sure yet. For the time being, see here for the temporary fix: 6d90eb6749ff9b5481315d55e8ab2c5617bcffa5

**Comment by marovira** [comment]
See next release. This issue has now been fixed.
