### ISSUE TITLE
Doxyfile generation does not handle paths with spaces leads to failure for make command

### ISSUE THREAD

**Issue by poanchen** [marovira/atlas#11]
Hey @marovira,

Just wanted to let you know that if you cloned the marovira/atlas repo in a folder name with spaces and you try to run the make command then it will get this build error,

> [ 99%] Generating HTML documentation
error: tag HTML_HEADER: header file `/home/poanchen/Downloads/folderwithspaces/atlas/external/glfw/docs/header.html' does not exist
external/glfw/docs/CMakeFiles/docs.dir/build.make:57: recipe for target 'external/glfw/docs/CMakeFiles/docs' failed
make[2]: *** [external/glfw/docs/CMakeFiles/docs] Error 1
CMakeFiles/Makefile2:1248: recipe for target 'external/glfw/docs/CMakeFiles/docs.dir/all' failed
make[1]: *** [external/glfw/docs/CMakeFiles/docs.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Things that I did:
I looked into the problem and **it WAS NOT a bug in your repo**. It was an edge case that was not covered in glfw/glfw. As the Doxyfile generation does not handle paths with spaces in them. As a result, I ended up creating an issue with them and they have resolved the issue quickly and it is now fixed/closed in their repo. The issue link is https://github.com/glfw/glfw/issues/1081. I am not sure what the action should you take but just wanted to let you know this. (as long as your folder name does not contains spaces then the make process will pass, so the workaround is make sure the folder name does not contains any spaces)

Thank you!

Cheers,
Baron

**Comment by marovira** [comment]
Hi @poanchen! Thanks for letting me know. Since it is a bug from GLFW, I'll just wait until they make a new release (the fix that you mentioned will be included in 3.3) and update the version in Atlas so everything works. Thanks!

**Comment by poanchen** [comment]
Sounds good to me. Thanks for the quick response!

Baron
