### ISSUE TITLE
Update Documentation for Wiki sources

### ISSUE THREAD

**Issue by MisterPotter** [marovira/atlas#5]
Links to code definitions within the Wiki (under classes) lead to dead pages. I'm sure that most code references do this at the moment. Pretty minor issue.

![image](https://cloud.githubusercontent.com/assets/9855524/22351246/d7e2f18e-e3cb-11e6-9186-f838f23b1547.png)

![image](https://cloud.githubusercontent.com/assets/9855524/22351270/e884cd46-e3cb-11e6-9d5a-5aee8a9efcaf.png)

**Comment by marovira** [comment]
Fixed in dc9f485. Turns out Jekyll was removing the files that had a leading underscore (and all html files that are related to source files have it). This removes Jekyll and fixes the broken links.
